# -*- mode: ruby -*-
# vi: set ft=ruby :

cluster={
 "jenkins.server"=>{:ip=>"192.168.56.10",:cpus=>2,:mem=>4048},
}

Vagrant.configure("2") do |config|

  cluster.each_with_index do |(hostname, info), index|

    config.vm.define hostname, autostart: true do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = "centos/7"
        config.vm.network "forwarded_port", guest_ip: "192.168.56.10", guest: 5000,  host_ip: "127.0.0.1", host: 5000
        override.vm.network "private_network", ip: "#{info[:ip]}" # Directory sync fails without this
        vb.name = hostname # sets gui name for VM
        config.vm.hostname = hostname
        vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
        config.vm.synced_folder "./", "/vagrant", type: "rsync", rsync__auto: true
        end # end provider
      end # end config
    end # end cluster
      # Use Vagrant Ansible provisioner
      config.vm.provision "ansible_local" do |ansible|
      # The path to the playbooks entry point
      ansible.playbook = "playbooks/run.yml"
      # Only run the roles with these tags
      ansible.tags = "install"
    end
end

