apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-empty-dir
  labels:
    app: nginx-empty-dir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-empty-dir
  template:
    metadata:
      labels:
        app: nginx-empty-dir
    spec:
        # END
      containers:
      - name: nginx-container
        image: nginx
        volumeMounts: 
        - name: nginx-storage
          mountPath: /usr/share/nginx/html
        ports:
          - containerPort: 80
            name: "http-server"
      volumes:
      - name: nginx-storage
        emptyDir: {}
          # TODO complete
          # END
