---
- hosts: all
  # Run commands as root
  become: true
  # Roles to be executed on these hosts
  roles:
  - role: flask_app/install
    tags: install

  - role: flask_app/healthchecks
    tags: check
